[[!pdoPage?
	&parents=`2`
    &element=`getTickets`
    &tpl=`eventsListItem`
    &tplWrapper=`eventsListOuter`
    &includeContent=`1`
    &includeTVs=`img,date,event_type,age_limit`
    &processTVs=`1`
    &where=`[{'pagetitle:IN:[]'}]`
]]